### ISSUE TITLE
VCF?

### ISSUE THREAD

**Issue by yannickwurm** [cropgeeks/flapjack#19]
Hello,

is there an easy way to get VCF into Flapjack? 

A related question is whether it can handle the large datasets (e.g. 1 million SNPs * 200 samples)

Thanks!
Yannick

**Comment by imilne** [comment]
If you don't mind getting your hands dirty with some command line Java, there is a utility you can run that can (try to) convert VCF to Flapjack's format for you, but with VCF being so complex I can't promise it'll work.

In Flapjack's install location's lib folder, run:
java -cp flapjack.jar jhi.flapjack.io.cmd.VcfToFJTabbedConverter
and it'll print usage instructions.

1 million by 200 samples should be fine I think.
