### ISSUE TITLE
Truncated position display with big position > 9.999.999

### ISSUE THREAD

**Issue by AxVE** [cropgeeks/flapjack#29]
Hi,

It looks like there is an issue on position display on QTL list ( Trait Data -> Quantitative Trait Loci (QTLs) ) : if a position is superior to 9.999.999 it will be truncated and only the first digit will be shown.

It reminds me a scientific number format but with the 'e8' hidden.

Here a small file with this problem
[bug_qtl.txt](https://github.com/cropgeeks/flapjack/files/4370731/bug_qtl.txt)

For information, I'm using :
* FlapJack: v1.19.09.04
* OS : Windows 10 64-bits
* Java: 11.0.3
* Memory of JVM : 4GB
* locale: fr_FR

**Comment by imilne** [comment]
Could you ping the raw data files to the help email address shown on Flapjack's main screen? I want to check whether it's a decimal separator formatting issue or an actual bug. Flapjack does have a setting in Prefs for telling it use dot for its decimal separator (which will override your French locale), but I couldn't say offhand whether it respects those settings with QTL etc.

**Comment by AxVE** [comment]
Do you mean the minimal test file I provided, a full file or unformatted data (gff) ?
Only the first case is possible. Unfortunately, I work on private data I can't share.

I generate the FlapMap file from an own script. There is not decimal separator in positions.

**Comment by imilne** [comment]
Ok, it looks like it's something related to the locales...fixable I'm sure.

With en_GB I see:

![image](https://user-images.githubusercontent.com/12698036/77441713-a6b26600-6de1-11ea-97b4-332d2e739334.png)

And with fr_FR:

![image](https://user-images.githubusercontent.com/12698036/77441755-b2059180-6de1-11ea-9fc7-12ee254dba28.png)

You might be able to work around it in the short term by setting your Interface Language to English in the Flapjack preferences which should override the automatic detection. Everything should look the same anyway as we have no French translations anyway.

**Comment by AxVE** [comment]
Using UK language (and forcing it) works on the full-dataset.
I'll pass the solution on our users.

Thanks and sorry for the inconvenience :)

**Comment by imilne** [comment]
Still a bug, so I'll leave the issue open until we've fixed it.
